sudo: requried
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t andyluchina/docker-react .

script:
  - docker run -e CI=true andyluchina/docker-react npm run test --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "docker-react"
  env: "DockerReact-env-1"
  bucket_name: "elasticbeanstalk-ap-southeast-1-913670747885"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
